name: Deploy

on:
  push:
    branches:
    - master
    paths:
    - 'reports/**'
    - '.github/workflows/**'

jobs:
  deploy-prod:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Download dependencies
        run: |
          install.packages("remotes")
          remotes::install_github("rstudio/connectapi")
        shell: Rscript {0}
      - name: Deploy
        env:
          CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }}
        run: |
          library(connectapi)
          client <- connect(host = "https://colorado.rstudio.com/rsc",
                              api_key = Sys.getenv("CONNECT_API_KEY"))
          bundle <- bundle_dir("reports")
          app_name <- "large_claims_summary"
          content <- deploy(client, bundle, name = app_name,
                                        access_type = "all")
          content %>%
            set_vanity_url("/med-claims-summary")
        shell: Rscript {0}
