name: Deploy

on:
  push:
    branches:
    - master
    paths:
    - 'reports/**'
    - '.github/workflows/**'

jobs:
  deploy-prod:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Download dependencies
        run: |
          remotes::install_github("rstudio/connectapi")
        shell: Rscript {0}
      - name: Deploy
        env:
          CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }}
        run: |
          client <- connectapi::connect(host = "https://colorado.rstudio.com/rsc",
                              api_key = Sys.getenv("CONNECT_API_KEY"))
          bundle <- connectapi::bundle_dir("reports")
          app_name <- "Large claims summary"
          content <- connectapi::deploy(client, bundle, name = app_name,
                                        access_type = "all")
        shell: Rscript {0}
